# go to sleep after one hour (1*60*60*1000ms)

CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

CONFIG_ZMK_SLEEP=y

#CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# MOUSE
CONFIG_ZMK_POINTING=n

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n

CONFIG_ZMK_DISPLAY=n

#Ã§Â¼Â©Ã¥Â°ÂÃ¦ÂÂ°Ã¥ÂÂ¼Ã¥ÂÂÃ¥Â°ÂÃ¥Â»Â¶Ã¨Â¿ÂÃ¤Â½ÂÃ¥Â¯Â¹Ã¨Â½Â´Ã¤Â½ÂÃ¥ÂÂÃ¨Â´Â¨Ã¨Â¦ÂÃ¦Â±ÂÃ¤Â¼ÂÃ¦ÂÂ´Ã©Â«Â Reducing the value will decrease the latency, but it will also place higher demands on the switching quality. If you are confident about the quality of the switch used on the keyboard, you can try smaller values, such as 1ms - 3ms.
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3

CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y

#macos logo open this config
#CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=y

# urchin.conf
#CONFIG_CUSTOM_ANIMATION_SPEED=900000

# Enable the Corne OLED Display (SSD1306)
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=10
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# Custom status screen (Scyan ZMK Display Module)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
CONFIG_LV_USE_CANVAS=y
CONFIG_LV_USE_IMG=y
CONFIG_SCYAN_ROTATION_90=y
CONFIG_SCYAN_ROTATION_270=n
CONFIG_SCYAN_INVERT=y
CONFIG_SCYAN_IDLE_TIMEOUT_MS=10000
CONFIG_SCYAN_USER_NAME="SCYAN"
CONFIG_ZMK_IDLE_TIMEOUT=60000
